package app.service;

import app.domain.Parrot;

import java.sql.*;
import java.text.SimpleDateFormat;

public class ParrotService {
    private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTablePerson = "CREATE TABLE Parrot(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(50) unique , dateOfBirth date ," +
            "weight double, isExotic varchar(50))";


    private Statement statement;
    public ParrotService() {
        try {
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Parrot".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTablePerson);

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
    public void addParrot(Parrot parrot) throws SQLException {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = format.format(parrot.getDateOfBirth());
        String insertIntoParrot = "INSERT INTO PARROT (name, dateOfBirth, weight, isExotic) VALUES ('" +
                parrot.getName() + "','" + dateString + "'," + parrot.getWeight()
                + ",'" + parrot.isExotic() + "'" +")";
        statement.executeUpdate(insertIntoParrot);
    }








    public void deleteParrot(String parrotName) throws SQLException {
        String dropFromParrot = "DELETE FROM Parrot WHERE name=" + "'" + parrotName + "'";
        statement.executeUpdate(dropFromParrot);
    }

}
