package app.service;

import java.sql.*;

public class ParrotService {
    private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTablePerson = "CREATE TABLE Parrot(id bigint GENERATED BY DEFAULT AS IDENTITY, latinName varchar(50), givenName varchar(50)," +
            "age integer, countryOfOrigin varchar(50))";


    private Statement statement;
    public ParrotService() {
        try {
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Parrot".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTablePerson);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

}
